# Generated by Django 3.2.3 on 2021-05-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='image',
            field=models.ImageField(default='ps.jpg', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='aadhar',
            field=models.BigIntegerField(max_length=12),
        ),
    ]
