# Generated by Django 3.2.3 on 2021-05-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voter', '0003_auto_20210529_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='profile',
            new_name='image',
        ),
    ]
